const pinataSDK = require('@pinata/sdk');
const fs = require('fs');
const path = require('path');

const pinata = pinataSDK('47b774d25a2a48417846', '7d3ff7ff52f5860193b85cb303ea762df924ec8f387513484e6a2836b4050cdd');

// Paths to the JSON files you want to upload
const customerDataPath = path.join(__dirname, 'data', 'customer_data.json');
const productCatalogPath = path.join(__dirname, 'data', 'product_catalog.json');

// Read the customer data JSON file
const customerData = require(customerDataPath); // Grabs the JSON data generated by csvToJson.js

// Read the product catalog JSON file
const productCatalog = require(productCatalogPath); // Grabs the product catalog JSON data

const uploadToPinata = async (data, fileName) => {
  const options = {
    pinataMetadata: {
      name: fileName,
      keyvalues: {
        description: `Data for ${fileName}`
      }
    },
    pinataOptions: {
      cidVersion: 1
    }
  };

  try {
    const result = await pinata.pinJSONToIPFS(data, options);
    console.log(`${fileName} uploaded to Piñata!`);
    console.log('IPFS Hash:', result.IpfsHash);
  } catch (err) {
    console.error(`Error uploading ${fileName}:`, err);
  }
};

// Upload both customer data and product catalog
uploadToPinata(customerData, 'Customer Data');
uploadToPinata(productCatalog, 'Product Catalog');
